name: Winery Guild
permalink: pretty
excerpt_separator: <!--more-->
collections:
  main-pages:
    output: true
  wineries:
    output: true
  states:
    output: true
  regions:
    output: true
  wines:
    output: true
  specials:
    output: true
  categories:
    output: true
  authors:
    output: true
  layouts: