name: Winery Guild
permalink: pretty
excerpt_separator: <!--more-->
collections:
  regions:
    output: true
  wineries:
    output: true
  wine:
    output: true
  specials:
    output: true
  mainpages:
    output: true
  categories:
  authors:
    output: true