name: Winery Guild
permalink: pretty
collections:
  main-pages:
    output: true
  wineries:
    output: true
  wines:
    output: true
  states:
    output: true
  regions:
    output: true
  specials:
    output: true
  categories:
    output: true
  authors:
    output: true
  layouts:
    output: true
shoppingcarts:
  - snipcart
  - foxycart